# syntax=docker/dockerfile:1

FROM node:22-bookworm-slim AS base
WORKDIR /app
ENV CI=true

FROM base AS deps
COPY package.json package-lock.json ./
COPY plugins/native-wearables ./plugins/native-wearables
RUN npm ci

FROM deps AS build
COPY . .

ARG VITE_API_BASE_URL=/api
ARG VITE_API_BASE_URL_PROD=/api
ARG VITE_API_TIMEOUT=30000
ARG VITE_APP_URL=
ARG VITE_SUPABASE_URL=
ARG VITE_SUPABASE_ANON_KEY=
ARG VITE_SUPABASE_PUBLISHABLE_KEY=
ARG VITE_SUPABASE_AUTH_REDIRECT_URL=
ARG VITE_PAYSTACK_PUBLIC_KEY=
ARG VITE_PAYSTACK_LIVE_PUBLIC_KEY=
ARG VITE_FLUTTERWAVE_PUBLIC_KEY=
ARG VITE_VAPID_PUBLIC_KEY=
ARG VITE_NATIVE_API_BASE_URL=
ARG VITE_NATIVE_REMOTE_PUSH_ENABLED=false

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_BASE_URL_PROD=$VITE_API_BASE_URL_PROD
ENV VITE_API_TIMEOUT=$VITE_API_TIMEOUT
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_AUTH_REDIRECT_URL=$VITE_SUPABASE_AUTH_REDIRECT_URL
ENV VITE_PAYSTACK_PUBLIC_KEY=$VITE_PAYSTACK_PUBLIC_KEY
ENV VITE_PAYSTACK_LIVE_PUBLIC_KEY=$VITE_PAYSTACK_LIVE_PUBLIC_KEY
ENV VITE_FLUTTERWAVE_PUBLIC_KEY=$VITE_FLUTTERWAVE_PUBLIC_KEY
ENV VITE_VAPID_PUBLIC_KEY=$VITE_VAPID_PUBLIC_KEY
ENV VITE_NATIVE_API_BASE_URL=$VITE_NATIVE_API_BASE_URL
ENV VITE_NATIVE_REMOTE_PUSH_ENABLED=$VITE_NATIVE_REMOTE_PUSH_ENABLED

RUN npm run build:full

FROM base AS prod-deps
ENV NODE_ENV=production
COPY package.json package-lock.json ./
COPY plugins/native-wearables ./plugins/native-wearables
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=prod-deps /app/plugins ./plugins
COPY --from=build /app/dist ./dist
COPY package.json ./

USER node
EXPOSE 3000

CMD ["node", "dist/api/server.js"]
