/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

/**
 * Push Notification Listener
 * Handles incoming push messages from the server
 */
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const { title, body, icon, badge, data } = payload;

    const options: any = {
      body: body || 'You have a new update from BabyLog.',
      icon: icon || '/logo.png',
      badge: badge || '/logo.png',
      vibrate: [100, 50, 100],
      data: data || {},
      actions: [
        { action: 'open', title: 'Open BabyLog' },
        { action: 'close', title: 'Dismiss' }
      ]
    };

    event.waitUntil(
      self.registration.showNotification(title || 'BabyLog Update', options)
    );
  } catch (err) {
    console.error('Failed to handle push notification:', err);
    // Generic fallback if JSON parsing fails
    event.waitUntil(
      self.registration.showNotification('BabyLog Notification', {
        body: event.data.text()
      })
    );
  }
});

/**
 * Notification Click Listener
 * Handles clicks on notifications or their actions
 */
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'close') return;

  const deepLink = event.notification.data?.deepLink || '/';

  // Open the app or focus the window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate to the deep link
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          (client as any).navigate(deepLink);
          return client.focus();
        }
      }
      // Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(deepLink);
      }
    })
  );
});

/**
 * Handle Service Worker updates
 */
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
