-- Source: ../database/sql/37-user-settings-care-profile-preferences.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

ALTER TABLE public.user_settings
ADD COLUMN IF NOT EXISTS care_profile_preferences JSONB NOT NULL DEFAULT '{}'::JSONB;

COMMENT ON COLUMN public.user_settings.care_profile_preferences IS
'Stores onboarding personalization choices such as baby stage, feeding style, priorities, and care-team focus.';
