-- Source: ../database/sql/14-analytics-usage.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- ANALYTICS & INSIGHTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS app_usage_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_date DATE,
  screen_name TEXT,
  duration_seconds INT,
  actions_count INT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS health_alert_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_code TEXT UNIQUE,
  cached_alerts JSONB,
  last_updated TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sync_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  table_name TEXT,
  action TEXT,
  record_data JSONB,
  synced BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  synced_at TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_app_usage_user_date ON app_usage_analytics(user_id, session_date);
