-- Source: ../DATABASE_SCHEMA.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Babies table
CREATE TABLE IF NOT EXISTS public.babies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  gender TEXT CHECK (gender IN ('boy', 'girl', 'other')),
  photo_url TEXT,
  country TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Sleep logs table
CREATE TABLE IF NOT EXISTS public.sleep_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  baby_id UUID NOT NULL REFERENCES public.babies(id) ON DELETE CASCADE,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  duration INTEGER NOT NULL, -- in minutes
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Feed logs table
CREATE TABLE IF NOT EXISTS public.feed_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  baby_id UUID NOT NULL REFERENCES public.babies(id) ON DELETE CASCADE,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('breast', 'bottle', 'solids')),
  left_duration INTEGER, -- minutes for breast
  right_duration INTEGER, -- minutes for breast
  amount NUMERIC, -- for bottle
  milk_type TEXT CHECK (milk_type IN ('breast', 'formula', 'other')),
  food_description TEXT, -- for solids
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Diaper logs table
CREATE TABLE IF NOT EXISTS public.diaper_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  baby_id UUID NOT NULL REFERENCES public.babies(id) ON DELETE CASCADE,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('wet', 'dirty', 'both')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Growth measurements table
CREATE TABLE IF NOT EXISTS public.growth_measurements (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  baby_id UUID NOT NULL REFERENCES public.babies(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  weight NUMERIC, -- kg or lb
  height NUMERIC, -- cm or inches
  head_circumference NUMERIC, -- cm or inches
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Vaccination records table
CREATE TABLE IF NOT EXISTS public.vaccination_records (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  baby_id UUID NOT NULL REFERENCES public.babies(id) ON DELETE CASCADE,
  vaccine_name TEXT NOT NULL,
  due_date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('scheduled', 'given', 'overdue', 'skipped')),
  given_date DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- User settings table
CREATE TABLE IF NOT EXISTS public.user_settings (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  units TEXT NOT NULL DEFAULT 'metric' CHECK (units IN ('metric', 'imperial')),
  language TEXT NOT NULL DEFAULT 'en',
  notifications_enabled BOOLEAN NOT NULL DEFAULT true,
  feeding_interval INTEGER NOT NULL DEFAULT 3, -- hours
  quiet_hours_start TIME,
  quiet_hours_end TIME,
  theme TEXT NOT NULL DEFAULT 'system' CHECK (theme IN ('light', 'dark', 'system')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_babies_user_id ON public.babies(user_id);
CREATE INDEX IF NOT EXISTS idx_sleep_logs_baby_id ON public.sleep_logs(baby_id);
CREATE INDEX IF NOT EXISTS idx_sleep_logs_start_time ON public.sleep_logs(start_time DESC);
CREATE INDEX IF NOT EXISTS idx_feed_logs_baby_id ON public.feed_logs(baby_id);
CREATE INDEX IF NOT EXISTS idx_feed_logs_timestamp ON public.feed_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_diaper_logs_baby_id ON public.diaper_logs(baby_id);
CREATE INDEX IF NOT EXISTS idx_diaper_logs_timestamp ON public.diaper_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_growth_measurements_baby_id ON public.growth_measurements(baby_id);
CREATE INDEX IF NOT EXISTS idx_growth_measurements_date ON public.growth_measurements(date DESC);
CREATE INDEX IF NOT EXISTS idx_vaccination_records_baby_id ON public.vaccination_records(baby_id);
CREATE INDEX IF NOT EXISTS idx_vaccination_records_due_date ON public.vaccination_records(due_date);

-- Enable RLS (Row Level Security)
ALTER TABLE public.babies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sleep_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feed_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diaper_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.growth_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vaccination_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for babies
CREATE POLICY "Users can view their own babies"
  ON public.babies FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own babies"
  ON public.babies FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own babies"
  ON public.babies FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own babies"
  ON public.babies FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for sleep_logs (indirect user_id through baby_id)
CREATE POLICY "Users can view their babies' sleep logs"
  ON public.sleep_logs FOR SELECT
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert sleep logs for their babies"
  ON public.sleep_logs FOR INSERT
  WITH CHECK (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their sleep logs"
  ON public.sleep_logs FOR UPDATE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their sleep logs"
  ON public.sleep_logs FOR DELETE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

-- RLS Policies for feed_logs
CREATE POLICY "Users can view their babies' feed logs"
  ON public.feed_logs FOR SELECT
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert feed logs for their babies"
  ON public.feed_logs FOR INSERT
  WITH CHECK (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their feed logs"
  ON public.feed_logs FOR UPDATE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their feed logs"
  ON public.feed_logs FOR DELETE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

-- RLS Policies for diaper_logs
CREATE POLICY "Users can view their babies' diaper logs"
  ON public.diaper_logs FOR SELECT
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert diaper logs for their babies"
  ON public.diaper_logs FOR INSERT
  WITH CHECK (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their diaper logs"
  ON public.diaper_logs FOR UPDATE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their diaper logs"
  ON public.diaper_logs FOR DELETE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

-- RLS Policies for growth_measurements
CREATE POLICY "Users can view their babies' growth measurements"
  ON public.growth_measurements FOR SELECT
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert growth measurements for their babies"
  ON public.growth_measurements FOR INSERT
  WITH CHECK (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their growth measurements"
  ON public.growth_measurements FOR UPDATE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their growth measurements"
  ON public.growth_measurements FOR DELETE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

-- RLS Policies for vaccination_records
CREATE POLICY "Users can view their babies' vaccination records"
  ON public.vaccination_records FOR SELECT
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can insert vaccination records for their babies"
  ON public.vaccination_records FOR INSERT
  WITH CHECK (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their vaccination records"
  ON public.vaccination_records FOR UPDATE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete their vaccination records"
  ON public.vaccination_records FOR DELETE
  USING (baby_id IN (SELECT id FROM public.babies WHERE user_id = auth.uid()));

-- RLS Policies for user_settings
CREATE POLICY "Users can view their own settings"
  ON public.user_settings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own settings"
  ON public.user_settings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own settings"
  ON public.user_settings FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own settings"
  ON public.user_settings FOR DELETE
  USING (auth.uid() = user_id);
