-- Source: ../database/sql/22-parent-wellness.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- PARENT WELLNESS & MENTAL HEALTH
-- ============================================================================

CREATE TABLE IF NOT EXISTS parent_wellness (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  stress_level INT CHECK (stress_level BETWEEN 1 AND 10),
  sleep_hours DECIMAL(3,1),
  mood_tags TEXT[],
  notes TEXT,
  checked_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parent_health_screening (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  screening_type TEXT NOT NULL CHECK (screening_type IN ('phq9', 'gad7', 'edinburgh_postnatal')),
  score INT,
  risk_level TEXT CHECK (risk_level IN ('normal', 'mild', 'moderate', 'severe')),
  screening_date DATE,
  recommended_action TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parent_support_resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  resource_type TEXT CHECK (resource_type IN ('article', 'hotline', 'therapist', 'group', 'app')),
  content_url TEXT,
  phone_number TEXT,
  availability TEXT,
  is_emergency BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_parent_wellness_user_id ON parent_wellness(user_id);
CREATE INDEX IF NOT EXISTS idx_parent_wellness_date ON parent_wellness(checked_at);
CREATE INDEX IF NOT EXISTS idx_parent_screening_user_id ON parent_health_screening(user_id);
