-- Source: ../database/sql/02-health-alerts.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- HEALTH ALERTS SYSTEM
-- ============================================================================

CREATE TABLE IF NOT EXISTS health_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('epidemic', 'seasonal', 'outbreak', 'warning')),
  disease_name TEXT NOT NULL,
  regions TEXT[] NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP,
  description TEXT,
  prevention_tips TEXT,
  affected_age_groups TEXT[] NOT NULL,
  source TEXT,
  data_source_url TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_health_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  alerts_enabled BOOLEAN DEFAULT true,
  alert_types TEXT[] DEFAULT ARRAY['epidemic', 'seasonal', 'outbreak'],
  notification_frequency TEXT DEFAULT 'immediate',
  primary_region TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS user_health_alerts_dismissed (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  alert_id UUID NOT NULL REFERENCES health_alerts(id) ON DELETE CASCADE,
  dismissed_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, alert_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_health_alerts_regions ON health_alerts USING GIN (regions);
CREATE INDEX IF NOT EXISTS idx_health_alerts_severity ON health_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_health_alerts_dates ON health_alerts(start_date, end_date);
