-- Source: ../database/sql/03-photo-management.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- PHOTO MANAGEMENT SYSTEM
-- ============================================================================

CREATE TABLE IF NOT EXISTS baby_photos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  baby_id UUID NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  storage_key TEXT,
  description TEXT,
  photo_date DATE NOT NULL,
  age_days INT,
  tags TEXT[] DEFAULT '{}',
  is_monthly_milestone BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS photo_collages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  baby_id UUID NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  collage_url TEXT,
  photos UUID[] NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_baby_photos_baby_id ON baby_photos(baby_id);
CREATE INDEX IF NOT EXISTS idx_baby_photos_date ON baby_photos(photo_date);
