-- Source: ../database/sql/39-health-connect-wearable-type.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- HEALTH CONNECT WEARABLE TYPE
-- ============================================================================

ALTER TABLE public.wearable_integrations
  DROP CONSTRAINT IF EXISTS wearable_integrations_device_type_check;

ALTER TABLE public.wearable_integrations
  ADD CONSTRAINT wearable_integrations_device_type_check
  CHECK (device_type IN ('apple_health', 'health_connect', 'fitbit', 'oura_ring', 'garmin'));
