-- Source: ../database/sql/10-voice-logs.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- VOICE LOGGING SYSTEM
-- ============================================================================

CREATE TABLE IF NOT EXISTS voice_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  baby_id UUID NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  audio_url TEXT NOT NULL,
  storage_key TEXT,
  transcription TEXT,
  duration_seconds INT,
  log_type TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS voice_recognition_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  voice_log_id UUID NOT NULL REFERENCES voice_logs(id) ON DELETE CASCADE,
  cry_type TEXT,
  confidence_score DECIMAL(3,2),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_voice_logs_baby_id ON voice_logs(baby_id);
