-- Source: ../database/sql/34-table-grants-for-health-logs-and-user-settings.sql
-- This file is generated by scripts/sync-supabase-migrations.mjs.
-- Edit the source SQL file instead of this generated mirror.

-- ============================================================================
-- TABLE GRANTS FOR HEALTH LOGS + USER SETTINGS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.health_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.user_settings TO authenticated;
